# Generated by Django 4.2.6 on 2023-10-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestProducts', '0002_remove_sessionlist_created_date_sessionlist_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('vector', models.BinaryField()),
            ],
        ),
    ]
