# Generated by Django 4.2.6 on 2023-10-29 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestProducts', '0003_wordvector'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wordvector',
            table='WordVector',
        ),
    ]
