# Generated by Django 4.2.6 on 2023-10-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestProducts', '0004_alter_wordvector_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlist',
            name='listCodeProduct',
            field=models.JSONField(),
        ),
    ]
