# Generated by Django 4.2.6 on 2023-10-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestProducts', '0005_alter_sessionlist_listcodeproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordvector',
            old_name='word',
            new_name='codeProduct',
        ),
        migrations.AlterField(
            model_name='sessionlist',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='wordvector',
            name='vector',
            field=models.CharField(max_length=10000, unique=True),
        ),
    ]
